name: Python type check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.257
